version: "3.3"
services:
  mongodb:
    image : mongo:4.4
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "password"
    ports:
      - 27017:27017
    restart: unless-stopped
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: ecom
    ports:
      - 5434:5432