// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: Protos/database/mongoclient/mongoclient.proto

package mongoclientmodel

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Emptyparam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Emptyparam) Reset() {
	*x = Emptyparam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Protos_database_mongoclient_mongoclient_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Emptyparam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Emptyparam) ProtoMessage() {}

func (x *Emptyparam) ProtoReflect() protoreflect.Message {
	mi := &file_Protos_database_mongoclient_mongoclient_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Emptyparam.ProtoReflect.Descriptor instead.
func (*Emptyparam) Descriptor() ([]byte, []int) {
	return file_Protos_database_mongoclient_mongoclient_proto_rawDescGZIP(), []int{0}
}

type Status struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Status) Reset() {
	*x = Status{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Protos_database_mongoclient_mongoclient_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_Protos_database_mongoclient_mongoclient_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_Protos_database_mongoclient_mongoclient_proto_rawDescGZIP(), []int{1}
}

func (x *Status) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Userid struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Userid) Reset() {
	*x = Userid{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Protos_database_mongoclient_mongoclient_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Userid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Userid) ProtoMessage() {}

func (x *Userid) ProtoReflect() protoreflect.Message {
	mi := &file_Protos_database_mongoclient_mongoclient_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Userid.ProtoReflect.Descriptor instead.
func (*Userid) Descriptor() ([]byte, []int) {
	return file_Protos_database_mongoclient_mongoclient_proto_rawDescGZIP(), []int{2}
}

func (x *Userid) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Addproduct struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Userid    string `protobuf:"bytes,1,opt,name=userid,proto3" json:"userid,omitempty"`
	Productid string `protobuf:"bytes,2,opt,name=productid,proto3" json:"productid,omitempty"`
}

func (x *Addproduct) Reset() {
	*x = Addproduct{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Protos_database_mongoclient_mongoclient_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Addproduct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Addproduct) ProtoMessage() {}

func (x *Addproduct) ProtoReflect() protoreflect.Message {
	mi := &file_Protos_database_mongoclient_mongoclient_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Addproduct.ProtoReflect.Descriptor instead.
func (*Addproduct) Descriptor() ([]byte, []int) {
	return file_Protos_database_mongoclient_mongoclient_proto_rawDescGZIP(), []int{3}
}

func (x *Addproduct) GetUserid() string {
	if x != nil {
		return x.Userid
	}
	return ""
}

func (x *Addproduct) GetProductid() string {
	if x != nil {
		return x.Productid
	}
	return ""
}

type Cart struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Productidlist []string `protobuf:"bytes,2,rep,name=productidlist,proto3" json:"productidlist,omitempty"`
}

func (x *Cart) Reset() {
	*x = Cart{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Protos_database_mongoclient_mongoclient_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cart) ProtoMessage() {}

func (x *Cart) ProtoReflect() protoreflect.Message {
	mi := &file_Protos_database_mongoclient_mongoclient_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cart.ProtoReflect.Descriptor instead.
func (*Cart) Descriptor() ([]byte, []int) {
	return file_Protos_database_mongoclient_mongoclient_proto_rawDescGZIP(), []int{4}
}

func (x *Cart) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Cart) GetProductidlist() []string {
	if x != nil {
		return x.Productidlist
	}
	return nil
}

var File_Protos_database_mongoclient_mongoclient_proto protoreflect.FileDescriptor

var file_Protos_database_mongoclient_mongoclient_proto_rawDesc = []byte{
	0x0a, 0x2d, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73,
	0x65, 0x2f, 0x6d, 0x6f, 0x6e, 0x67, 0x6f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f, 0x6d, 0x6f,
	0x6e, 0x67, 0x6f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x10, 0x6d, 0x6f, 0x6e, 0x67, 0x6f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x22, 0x0c, 0x0a, 0x0a, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x22,
	0x1e, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22,
	0x18, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x69, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x42, 0x0a, 0x0a, 0x61, 0x64, 0x64,
	0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x69, 0x64, 0x12,
	0x1c, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x69, 0x64, 0x22, 0x3c, 0x0a,
	0x04, 0x63, 0x61, 0x72, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x24, 0x0a, 0x0d, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x69, 0x64, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0d, 0x70, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x69, 0x64, 0x6c, 0x69, 0x73, 0x74, 0x32, 0x94, 0x04, 0x0a, 0x12,
	0x4d, 0x6f, 0x6e, 0x67, 0x6f, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x47, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x43, 0x61, 0x72, 0x74, 0x49, 0x74, 0x65,
	0x6d, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x18, 0x2e, 0x6d, 0x6f, 0x6e, 0x67,
	0x6f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x75, 0x73, 0x65,
	0x72, 0x69, 0x64, 0x1a, 0x16, 0x2e, 0x6d, 0x6f, 0x6e, 0x67, 0x6f, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x63, 0x61, 0x72, 0x74, 0x12, 0x43, 0x0a, 0x0d, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x4e, 0x65, 0x77, 0x43, 0x61, 0x72, 0x74, 0x12, 0x18, 0x2e, 0x6d,
	0x6f, 0x6e, 0x67, 0x6f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e,
	0x75, 0x73, 0x65, 0x72, 0x69, 0x64, 0x1a, 0x18, 0x2e, 0x6d, 0x6f, 0x6e, 0x67, 0x6f, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x4a, 0x0a, 0x10, 0x41, 0x64, 0x64, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x54, 0x6f,
	0x43, 0x61, 0x72, 0x74, 0x12, 0x1c, 0x2e, 0x6d, 0x6f, 0x6e, 0x67, 0x6f, 0x63, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x61, 0x64, 0x64, 0x70, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x1a, 0x18, 0x2e, 0x6d, 0x6f, 0x6e, 0x67, 0x6f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x48, 0x0a, 0x12,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x61, 0x72, 0x74, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x18, 0x2e, 0x6d, 0x6f, 0x6e, 0x67, 0x6f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x69, 0x64, 0x1a, 0x18, 0x2e, 0x6d,
	0x6f, 0x6e, 0x67, 0x6f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x53, 0x0a, 0x19, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x43, 0x61, 0x72, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x42, 0x79, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x49, 0x64, 0x12, 0x1c, 0x2e, 0x6d, 0x6f, 0x6e, 0x67, 0x6f, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x61, 0x64, 0x64, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x1a, 0x18, 0x2e, 0x6d, 0x6f, 0x6e, 0x67, 0x6f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x42, 0x0a, 0x0c, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x6f, 0x75, 0x74, 0x43, 0x61, 0x72, 0x74, 0x12, 0x18, 0x2e, 0x6d, 0x6f,
	0x6e, 0x67, 0x6f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x75,
	0x73, 0x65, 0x72, 0x69, 0x64, 0x1a, 0x18, 0x2e, 0x6d, 0x6f, 0x6e, 0x67, 0x6f, 0x63, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x41, 0x0a, 0x07, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x79, 0x12, 0x1c, 0x2e, 0x6d, 0x6f, 0x6e,
	0x67, 0x6f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x65, 0x6d,
	0x70, 0x74, 0x79, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x1a, 0x18, 0x2e, 0x6d, 0x6f, 0x6e, 0x67, 0x6f,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x42, 0x34, 0x5a, 0x32, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x63, 0x61, 0x70, 0x73, 0x6c, 0x6f, 0x63, 0x6b, 0x2d, 0x69, 0x6e, 0x63, 0x2f, 0x67, 0x72,
	0x70, 0x63, 0x2d, 0x64, 0x65, 0x6d, 0x6f, 0x3b, 0x6d, 0x6f, 0x6e, 0x67, 0x6f, 0x63, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_Protos_database_mongoclient_mongoclient_proto_rawDescOnce sync.Once
	file_Protos_database_mongoclient_mongoclient_proto_rawDescData = file_Protos_database_mongoclient_mongoclient_proto_rawDesc
)

func file_Protos_database_mongoclient_mongoclient_proto_rawDescGZIP() []byte {
	file_Protos_database_mongoclient_mongoclient_proto_rawDescOnce.Do(func() {
		file_Protos_database_mongoclient_mongoclient_proto_rawDescData = protoimpl.X.CompressGZIP(file_Protos_database_mongoclient_mongoclient_proto_rawDescData)
	})
	return file_Protos_database_mongoclient_mongoclient_proto_rawDescData
}

var file_Protos_database_mongoclient_mongoclient_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_Protos_database_mongoclient_mongoclient_proto_goTypes = []interface{}{
	(*Emptyparam)(nil), // 0: mongoclientmodel.emptyparam
	(*Status)(nil),     // 1: mongoclientmodel.status
	(*Userid)(nil),     // 2: mongoclientmodel.userid
	(*Addproduct)(nil), // 3: mongoclientmodel.addproduct
	(*Cart)(nil),       // 4: mongoclientmodel.cart
}
var file_Protos_database_mongoclient_mongoclient_proto_depIdxs = []int32{
	2, // 0: mongoclientmodel.MongoClientService.GetCartItemByUserId:input_type -> mongoclientmodel.userid
	2, // 1: mongoclientmodel.MongoClientService.CreateNewCart:input_type -> mongoclientmodel.userid
	3, // 2: mongoclientmodel.MongoClientService.AddProductToCart:input_type -> mongoclientmodel.addproduct
	2, // 3: mongoclientmodel.MongoClientService.DeleteCartByUserId:input_type -> mongoclientmodel.userid
	3, // 4: mongoclientmodel.MongoClientService.DeleteCartItemByProductId:input_type -> mongoclientmodel.addproduct
	2, // 5: mongoclientmodel.MongoClientService.CheckoutCart:input_type -> mongoclientmodel.userid
	0, // 6: mongoclientmodel.MongoClientService.Healthy:input_type -> mongoclientmodel.emptyparam
	4, // 7: mongoclientmodel.MongoClientService.GetCartItemByUserId:output_type -> mongoclientmodel.cart
	1, // 8: mongoclientmodel.MongoClientService.CreateNewCart:output_type -> mongoclientmodel.status
	1, // 9: mongoclientmodel.MongoClientService.AddProductToCart:output_type -> mongoclientmodel.status
	1, // 10: mongoclientmodel.MongoClientService.DeleteCartByUserId:output_type -> mongoclientmodel.status
	1, // 11: mongoclientmodel.MongoClientService.DeleteCartItemByProductId:output_type -> mongoclientmodel.status
	1, // 12: mongoclientmodel.MongoClientService.CheckoutCart:output_type -> mongoclientmodel.status
	1, // 13: mongoclientmodel.MongoClientService.Healthy:output_type -> mongoclientmodel.status
	7, // [7:14] is the sub-list for method output_type
	0, // [0:7] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Protos_database_mongoclient_mongoclient_proto_init() }
func file_Protos_database_mongoclient_mongoclient_proto_init() {
	if File_Protos_database_mongoclient_mongoclient_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Protos_database_mongoclient_mongoclient_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Emptyparam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Protos_database_mongoclient_mongoclient_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Status); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Protos_database_mongoclient_mongoclient_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Userid); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Protos_database_mongoclient_mongoclient_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Addproduct); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Protos_database_mongoclient_mongoclient_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cart); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Protos_database_mongoclient_mongoclient_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_Protos_database_mongoclient_mongoclient_proto_goTypes,
		DependencyIndexes: file_Protos_database_mongoclient_mongoclient_proto_depIdxs,
		MessageInfos:      file_Protos_database_mongoclient_mongoclient_proto_msgTypes,
	}.Build()
	File_Protos_database_mongoclient_mongoclient_proto = out.File
	file_Protos_database_mongoclient_mongoclient_proto_rawDesc = nil
	file_Protos_database_mongoclient_mongoclient_proto_goTypes = nil
	file_Protos_database_mongoclient_mongoclient_proto_depIdxs = nil
}
